### ISSUE TITLE
What's the license? 🙂

### ISSUE THREAD

**Issue by yogiben** [cubedhuang/nimi.li#7]

**Comment by cubedhuang** [comment]
Most of the dictionary data comes from [jasima Linku](https://github.com/lipu-linku/jasima) licensed under CC BY-SA 4.0, so this repository would have to be licensed under that or some compatible license. This website is under GPL-3.0 which is compatible with CC BY-SA 4.0.

**Comment by zool-99** [comment]
Hi Yogiben,
I hope you see this message, I looking for help with one of your first encrypted bitwala and it's impossible to open it, I have the password and the .pdf doc. As I read on internet someone found his solution contacting you directly. I already try bitwala support without this getting solved.

Sorry I know this is the wrong place, but I don't see way to send private message on Github (I am new to Github sorry if this was possible)

Thanks.

**Comment by yogiben** [comment]
@zool-99 thanks for reaching out. I haven't been actively involved for a while, but Jan and Denis should be able to help you out.

https://support.bitwala.com/hc/en-gb

**Comment by zool-99** [comment]
ok thanks for the feedback, I hope it will work this time, I will ask them for help. 

Glad to see Bitwala is still running even if the service kind of changed a little.

In fact trouble is just I coming late and the tool used to dectrypt is not online anymore, I will keep you updated after my support request get an answer.

**Comment by zool-99** [comment]
Hi Yogiben,

Sorry to say they are not helpful here is the answer: "
I am sorry to say, but the website for recovery is offline since the insolvency. "

I specified I ask to Jan and Devis to answer, but got this king of automatic answer from David.

Also I have to say wow ! this answer, just wow like ok "thanks for using our services in the past. We can't help".

No sorry for you loss, not any you could try this or anything. Just thank for reaching us, bye...

**Comment by zool-99** [comment]
Bitwala encrypted this, so How can I decrypt ? I need to know how to build a software a anything I can try. But for this I need some information.

With the encrypted .pdf It's possible to recover the full key ? Or you cut this half in the .pdf half on your side ? I need to understand how to recover this, time are hard and this can be some helping money. I own it but can't access it.

**Comment by yogiben** [comment]
Hi,

I will try my best to help, but please understand I've been out of the business for quite some time.

My memory is that the PDF has 2 of 3 keys which lets you access funds. Please also see this tool: https://github.com/bitwala/bitgo-recovery-tool

**Comment by zool-99** [comment]
Hi Yogiben,

real thanks for your time looking into this, ok I will try the bitgo recovery tool.

Just to give feedback from my support ticket
So sad I awake myself just too late lol 
Here is last Bitwala answers :
"The support for legacy wallets from 2017 and before, was discontinued in December 2022 when Nuri stopped operations due to its insolvency. "
So few month ago I could get help with Bitwala support but now it's over.
